# Generated by Django 4.2.6 on 2023-12-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('item_dtls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.cart')),
            ],
        ),
    ]
