# Generated by Django 4.2.6 on 2024-01-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
