# Generated by Django 4.2.6 on 2024-01-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0006_product_category_services_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='suspense',
            field=models.BooleanField(default=True),
        ),
    ]
