# Generated by Django 4.2.6 on 2024-01-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0007_petshop_suspense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='services',
            name='accept',
        ),
    ]
