# Generated by Django 4.2.6 on 2024-01-08 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0008_remove_product_accept_remove_services_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Paw.petshop'),
            preserve_default=False,
        ),
    ]
