# Generated by Django 4.2.6 on 2024-01-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0009_notification_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeanorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('total', models.IntegerField()),
                ('item_dtls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
