# Generated by Django 4.2.6 on 2024-01-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0010_placeanorder_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
