# Generated by Django 4.2.6 on 2024-01-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0011_cart_total_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.petuser')),
            ],
        ),
    ]
