# Generated by Django 4.2.6 on 2024-01-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0012_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopNotification',
        ),
    ]
