# Generated by Django 4.2.6 on 2024-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0013_delete_shopnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(upload_to='static'),
        ),
    ]
