# Generated by Django 5.1.4 on 2026-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0015_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
