# Generated by Django 5.1.4 on 2026-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0017_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='pettype',
            field=models.CharField(blank=True, default='All Pets', max_length=30),
        ),
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
