# Generated by Django 5.1.4 on 2026-03-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0018_product_description_product_pettype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
        migrations.CreateModel(
            name='ShopNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.notification')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paw.petshop')),
            ],
            options={
                'unique_together': {('shop', 'notification')},
            },
        ),
    ]
