# Generated by Django 4.2.6 on 2026-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0019_notification_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshop',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
