# Generated by Django 4.2.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paw', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(help_text="Name of the pet being diagnosed", max_length=100)),
                ('pet_age', models.PositiveIntegerField(help_text="Age of the pet in years")),
                ('animal_type', models.CharField(
                    choices=[
                        ('dog', 'Dog'),
                        ('cat', 'Cat'),
                        ('bird', 'Bird'),
                        ('rabbit', 'Rabbit'),
                        ('hamster', 'Hamster'),
                        ('fish', 'Fish'),
                        ('reptile', 'Reptile'),
                    ],
                    help_text="Type of animal",
                    max_length=20
                )),
                ('symptoms_description', models.TextField(help_text="Free-text description of symptoms provided by user")),
                ('symptoms_matched', models.JSONField(
                    default=list,
                    help_text="List of matched symptom keywords from the AI engine"
                )),
                ('predicted_illness', models.CharField(help_text="Primary predicted illness", max_length=200)),
                ('confidence_score', models.FloatField(help_text="AI confidence score (0.0 - 1.0)")),
                ('severity', models.CharField(
                    choices=[
                        ('low', 'Low'),
                        ('moderate', 'Moderate'),
                        ('high', 'High'),
                        ('critical', 'Critical'),
                    ],
                    help_text="Assessed severity level",
                    max_length=10
                )),
                ('recommended_actions', models.JSONField(
                    default=list,
                    help_text="List of recommended actions from the AI"
                )),
                ('differential_diagnoses', models.JSONField(
                    default=list,
                    help_text="Alternative possible diagnoses with scores"
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    help_text="The user who requested this diagnosis",
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='diagnosis_records',
                    to='Paw.petuser'
                )),
            ],
            options={
                'verbose_name': 'Diagnosis Record',
                'verbose_name_plural': 'Diagnosis Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_rating', models.CharField(
                    choices=[
                        ('accurate', 'Accurate'),
                        ('partially_accurate', 'Partially Accurate'),
                        ('inaccurate', 'Inaccurate'),
                        ('unknown', 'Unknown'),
                    ],
                    help_text="How accurate the diagnosis was",
                    max_length=20
                )),
                ('veterinarian_diagnosis', models.TextField(
                    blank=True,
                    help_text="Actual diagnosis from a vet (if available)",
                    default=''
                )),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(
                    help_text="The diagnosis this feedback is for",
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='feedback',
                    to='PetHealthAI.diagnosisrecord'
                )),
            ],
        ),
    ]
