# Generated by Django 5.1.4 on 2026-03-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paw', '0018_product_description_product_pettype_and_more'),
        ('PetHealthAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='account_type',
            field=models.CharField(default='user', help_text="'user' for pet owners, 'shop' for shop owners", max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='The shop that requested this diagnosis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to='Paw.petshop'),
        ),
        migrations.AlterField(
            model_name='diagnosisfeedback',
            name='diagnosis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='PetHealthAI.diagnosisrecord'),
        ),
        migrations.AlterField(
            model_name='diagnosisfeedback',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosisfeedback',
            name='veterinarian_diagnosis',
            field=models.TextField(blank=True, help_text='Actual diagnosis from a vet (if available)'),
        ),
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who requested this diagnosis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_records', to='Paw.petuser'),
        ),
    ]
